before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

test_python2:
  image: python:2.7
  script:
    - python art_test.py -v

test_python3:
  image: python:3.5
  script:
    - python art_test.py -v
