"""submission groups, email verifier

Revision ID: 376f3e0232fd
Revises: 9ad9ac463bbb
Create Date: 2018-04-08 15:21:45.470845

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '376f3e0232fd'
down_revision = '9ad9ac463bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'submission_group',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('saved_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'submission_group', ['group_id'], ['id'])
        batch_op.drop_column('submitted')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('email_reset_verifier', sa.String(length=16), nullable=True)
        )
        batch_op.create_unique_constraint(None, ['email_reset_verifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_reset_verifier')

    with op.batch_alter_table('saved_submission', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'submitted',
                mysql.TINYINT(display_width=1),
                server_default=sa.text("'0'"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')

    op.drop_table('submission_group')
    # ### end Alembic commands ###
